stages:
  - build
  - deploy

########################################################################
#                        MASTER BRANCH                                 #
########################################################################
build prod:
  image: node:12.15.0-stretch
  stage: build
  only:
    - master
  script:
    # Install vuecli
    - npm install -g @vue/cli@latest
    # Install dependencies
    - npm install
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy prod:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://covid.attestation
    - aws cloudfront create-invalidation --distribution-id=E2HZ18BQ278SQN --paths "/*"
